__all__ = [ 'resFunc_gaussian',
            'resFunc_pseudoVoigt',
            'ECFunc_pseudoVoigt',
            'ECFunc_Gaussian',
            'D2OFunc_singleLorentzian_Min',
            'D2OFunc_lorentzian_and_elastic_Min',
            'QENS_prot_powder_doubleLorentzian_BH',
            'QENS_prot_powder_singleLorentzian_BH',
            'QENS_water_powder_BH',
            'QENS_water_powder_minuit',
            'QENS_protein_liquid_analytic_voigt_BH',
            'QENS_protein_liquid_analytic_voigt_CF',
            'TempRamp_gaussian',
            'TempRamp_q4',
            'FWS_protein_liquid_BH',
            'FWS_protein_liquid_CF',
            'FWS_protein_liquid_withImmobileFrac_BH',
            ]
